python/django/yetAnotherHelloWorld/main/urls.py
from django.conf.urls import include, url
from django.views.static import serve
from django.contrib import admin
from main import views as main
from library import views as library
from contacts import views as contacts
from django.conf import settings

urlpatterns = [
    url(r'^$', main.index),
    url(r'^restful/$', library.book),
    url(r'^now/$', main.dateNow, {'template': 'now.html'}),
    url(r'^book/(?P<year>\d{4})/$', main.book),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^search/$', library.search),
    url(r'^contacts/$', contacts.contacts),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT,
        }),
    ]

python/django/yetAnotherHelloWorld/contacts/models.py
from django.db import models

# Create your models here.

python/django/yetAnotherHelloWorld/library/models.py
# -*- coding: utf-8 -*-
from django.db import models


class Editor(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField(blank=True)

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Editors"

    def __unicode__(self):
        return self.name


class Author(models.Model):
    name = models.CharField(max_length=30)
    lastName = models.CharField(max_length=40)
    email = models.EmailField(blank=True, verbose_name='e-­mail')

    class Meta:
        ordering = ["lastName"]
        verbose_name_plural = "Authors"

    def __unicode__(self):
        return '%s %s' % (self.name, self.lastName)


class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    editor = models.ForeignKey(Editor)
    date_published = models.DateField(blank=True, null=True)
    cover = models.ImageField(upload_to='covers')

    class Meta:
        ordering = ["title"]
        verbose_name_plural = "Books"

    def __unicode__(self):
        return self.title

python/django/yetAnotherHelloWorld/contacts/forms.py
# -*- coding: utf-8 -*-

from django import forms


class formContact(forms.Form):
    reason = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, label='you email')
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("¡Se requieren mínimo 4 palabras!")
        return message

python/django/yetAnotherHelloWorld/contacts/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from contacts.forms import formContact
from django.core.mail import send_mail
from django.http import HttpResponseRedirect


def contacts(request):
    if request.method == 'POST':
        form = formContact(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            '''send_mail(
                cd['asunto'],
                cd['mensaje'],
                cd.get('email', 'noreply@example.com'),
                    ['siteowner@example.com'],
             )'''
            return HttpResponseRedirect('/now/')
    else:
        form = formContact(initial={'reason': 'Your web is cool!!'})

    return render(request, 'contactForm.html', {'form': form})

python/django/yetAnotherHelloWorld/library/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from library.models import Book
from django.http import HttpResponse, Http404


def list_object(request, model):
    listObjects = model.objects.all()
    template = 'library/%s_lista.html' % model.__name__.lower()
    return render(request, template, {'listObject': listObjects})


def search(request):
    errors = []
    if 'query' in request.GET:
        query = request.GET['query']
        if not query:
            errors.append('Por favor introduce un término de búsqueda.')
        elif len(query) > 20:
            errors.append('''Por favor introduce un término de búsqueda menor
            a 20 caracteres.''')
        else:
            books = Book.objects.filter(title__icontains=query)
            return render(request, 'result.html',
            {'books': books, 'query': query})

    return render(request, 'searchForm.html', {'errors': errors})


def book(request):
    def GET(request):
        return HttpResponse("GET response")

    def POST(request):
        return HttpResponse("POST response")

    if request.method == 'GET':
        return GET(request)
    elif request.method == 'POST':
        return POST(request)
    raise Http404

python/django/yetAnotherHelloWorld/main/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse, Http404
from django.shortcuts import render
from django.shortcuts import render_to_response
from library.models import Book
import datetime


def index(request):
    return HttpResponse('hello world')


def debug(request):
    valor = request.META.items()
    valor.sort()
    html = []
    for k, v in valor:
        html.append('<tr><td><strong>%s</strong></td><td>%s</td></tr>' % (k, v))
    return HttpResponse('<table>%s</table>' % '\n'.join(html))


def dateNow(request, template):
    itsNow = datetime.datetime.now()
    return render(request, 'now.html', {'now': itsNow})


def list_library(request, template):
    list_books = Book.objects.order_by('name')
    return render_to_response('now.html', {'now': list_books})


def book(request, year):
    try:
        offset = int(year)
    except ValueError:
        raise Http404()
    html = """<html><body><h1>El anyo es: %s</h1>
        </body></html>""" % (offset)
    return HttpResponse(html)

python/django/yetAnotherHelloWorld/main/templates/contactForm.html
<!Doctype>
<html>
<head>
    <title>Contactanos</title>
    <style type="text/css">
        ul.errorlist {
            margin: 0;
            padding: 0;
        }
        .errorlist li {
            background­color: red;
            color: white;
            display: block;
            font­size: 10px;
            margin: 0 0 3px;
            padding: 4px 5px;
        }
        label {
            display: block;
            margin-top: 30px;
            font-weight: 700;
        }
    </style>
</head>
<body>
    <h1>Contact us</h1>

 {% if form.errors %}
    <p style="color: red;">
    Por favor corrige lo siguiente:
    </p>
{% endif %}

    <form action="" method="post">{% csrf_token %}
        <div class="field">
            {{ form.reason.errors }}
                <label for="id_reason">Reason:</label>
            {{ form.reason }}
        </div>

        <div class="field">
            {{ form.email.errors }}
               <label for="id_email">email:</label>
           {{ form.email }}
        </div>

        <div class="field">
            {{ form.message.errors }}
                <label for="id_message">Message:</label>
            {{ form.message }}
        </div>

        <input type="submit" value="Enviar">
    </form>
</body>
</html>

python/django/yetAnotherHelloWorld/main/templates/errors.html
{% if errors %}
    <ul>
    {% for error in errors %}
        <li>{{ error }}</li>
    {% endfor %}
    </ul>
{% endif %}

python/django/yetAnotherHelloWorld/main/templates/index.html
<html>
<head>
  <meta charset="utf-8" />
  <title>Wellcome!</title>
</head>
<body>
  <h1>Yet another Hello World</h1>
  {% block content %}
  {% endblock %}
</body>
</html>

python/django/yetAnotherHelloWorld/main/templates/now.html
{% extends "index.html" %}

{% block content %}
    <p>Today is: {{ now }}</p>
{% endblock %}

python/django/yetAnotherHelloWorld/main/templates/result.html
{% extends "index.html" %}

{% block content %}
<p>Estas buscado: <strong>{{ query }}</strong></p>

{% if books %}
    <p>Libros encontrados: {{ books|length }} libro{{ books|pluralize }}.</p>
    <ul>
        {% for book in books %}
            <li>{{ book.title }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>Ningún libro coincide con el criterio de búsqueda.</p>
{% endif %}
{% endblock %}

python/django/yetAnotherHelloWorld/main/templates/searchForm.html
<html>
<head>
    <title>Buscar</title>
</head>
<body>
    {% if errors %}
        <ul>
            {% for error in errors %}
            <li style="color: red;">{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form action="/search/" method="get">
        <input type="text" name="query">
        <input type="submit" value="Buscar">
    </form>
</body>